FitApp/Models/Abs.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FitApp.Models
{
    public class Abs
    {
        [Key]
        [Required]
        public byte ExerciseId { get; set; }
        [Required]
        public string ExerciseName { get; set; }
        [Required]
        public string ExerciseLevel { get; set; }
        [Required]
        public string ExerciseEquipment { get; set; }

    }
}

FitApp/Models/Workouts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FitApp.Models
{
    public class Workouts
    {
        [Key]
        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int WorkoutId { get; set; }
        [Required]
        public int ExerciseId { get; set; }
        [Required]
        public DateTime WorkoutDate { get; set; }
        [Required]
        public byte FirstSet { get; set; }
        public byte SecondSet { get; set; }
        public byte ThirdSet { get; set; }
        public byte FourthSet { get; set; }
        public byte FifthSet { get; set; }
    }
}

FitApp/Controllers/AbsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FitApp.Models;
using Microsoft.Ajax.Utilities;

namespace FitApp.Controllers
{
    public class AbsController : Controller
    {
        private ApplicationDbContext _context;

        public AbsController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Abs
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Workout(int NumberOfExercises, string ExerciseLevel, string pullupbar, string abwheel, string weights)
        {
            bool hasEquipment = !(pullupbar.IsNullOrWhiteSpace() && abwheel.IsNullOrWhiteSpace() && weights.IsNullOrWhiteSpace());
            List<Abs> exercises;

            if (hasEquipment)
            {
                exercises = _context.Abs.OrderBy(e => Guid.NewGuid())
                    .Where(e => (e.ExerciseLevel == ExerciseLevel
                                 && (hasEquipment
                                     || e.ExerciseEquipment == pullupbar
                                     || e.ExerciseEquipment == abwheel
                                     || e.ExerciseEquipment == weights
                                     ))).Take(NumberOfExercises).ToList();
            }
            else
            {
                exercises = _context.Abs.OrderBy(e => Guid.NewGuid())
                    .Where(e => (e.ExerciseLevel == ExerciseLevel && e.ExerciseEquipment == "none")).Take(NumberOfExercises).ToList();
            }
            

            if (!exercises.Any())
                return new HttpNotFoundResult();
            else
                return View(exercises);
        }
    }
}

FitApp/Controllers/Api/WorkoutsController.cs
using System;
using System.CodeDom;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using FitApp.Models;

namespace FitApp.Controllers.Api
{
    public class WorkoutsController : ApiController
    {
        private ApplicationDbContext _context;

        public WorkoutsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET /api/workouts
        public IEnumerable<Workouts> GetWorkouts()
        {
            return _context.Workouts.ToList();
        }

        //POST /api/workouts
        [HttpPost]
        public void CreateWorkout(string ExerciseName, byte first, byte second, byte third, byte fouth, byte fifth)
        {
            var exerciseId = _context.Exercises.Where(c => c.ExerciseName == ExerciseName).ToList();
            
            
                
                       

           
            _context.SaveChanges();

            
        }

        

    }
}

FitApp/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FitApp.Models;

namespace FitApp.App_Start
{
    public class WorkoutController : Controller
    {
        private ApplicationDbContext _context;

        public WorkoutController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Workout
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Enter()
        {
            return View();
        }



    }
}

FitApp/Views/Abs/Index.cshtml
@using System.Web.Mvc.Html

@{
    ViewBag.Title = "Index";
    
}

<h2>Index</h2>



@using (Html.BeginForm("Workout", "Abs"))
{
    <div class="form-group">
        @Html.Label("NumberOfExercises", "Number of Exercises:")
        @Html.DropDownList("NumberOfExercises", Enumerable.Range(1, 9).Select(i => new SelectListItem {Text = i.ToString(), Value = i.ToString()}), new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.Label("ExerciseLevel", "Your Fitness Level:")
        @Html.DropDownList("ExerciseLevel", new List<SelectListItem>()
        {
            new SelectListItem() {Text = "Beginner", Value = "beginner"},
            new SelectListItem() {Text = "Intermediate", Value = "intermediate"},
            new SelectListItem() {Text = "Advanced", Value = "advanced"}
        }, new {@class = "form-control"})
    </div>
    @Html.Label("Equipment", "Choose Equipment: ")
    <div class="checkbox">
        <label><input type="checkbox" name="pullupbar" value="pullupbar"> Pull Up Bar</label>
    </div>
    <div class="checkbox">
        <label><input type="checkbox" name="abwheel" value="abwheel"> Ab Wheel</label>
    </div>
    <div class="checkbox">
        <label><input type="checkbox" name="weights" value="weights"> Weights</label>
    </div>
    


        <button type="submit" class="btn btn-primary">Get</button>


        }

FitApp/Views/Abs/Workout.cshtml
@model IEnumerable<FitApp.Models.Abs>
@{
    ViewBag.Title = "Workout";
}

<h2>Workout</h2>

@foreach (var exercise in Model)
{
    <button class="btn btn-link js-instructions">
        @exercise.ExerciseName
    </button><br/>
}

@section scripts
{
    <script>
        $(document).ready(function() {
            $(".js-instructions").on("click", function () {
                bootbox.alert({
                    message: "Here goes video or instructions...",
                    backdrop: true
                });
            });
        })
    </script>
}